### ISSUE TITLE
Exit codes for easy use with Continuous Integration

### ISSUE THREAD

**Issue by AlexanderMann** [kkinnear/lein-zprint#6]
# Motivation

Hello! Just starting out a new project and trying to setup linting in CI s best practices. Decided to give Zprint a go. Had trouble getting the binaries setup in an `alpine` install of Clojure, so decided to use `lein-zprint`.

Things are working fine locally, and run just fine in CI now, however trying to integrate failures has been tricky. We'd like to avoid needing to pull in `git` to do something like `git status --diff` or `porcelain`, but haven't been able to find a way to trigger a failure off of `lein-zprint` regularly.

We attempted leveraging setting `old? true` and then detecting the presence of those files. However, it looks like an `old` file is created _every_ time, no matter the status.

## Goals

We would like either a summary line we can grok for, or a non 0 exit code, when there are changes that need to be checked in.

## Setup

Our configuration presently looks like this:

```edn
(defproject mvp "0.1.0-SNAPSHOT"
  :dependencies [[org.clojure/clojure "1.10.1"]]
  :plugins [[lein-zprint "1.1.1"]]
  :main ^:skip-aot mvp.core
  :target-path "target/%s"
  :profiles {:uberjar {:aot :all
                       :jvm-opts ["-Dclojure.compiler.direct-linking=true"]}}
  :zprint {:map {:comma? false}
           :old? false
           :reader-cond {:comma? false}
           :style :indent-only})
```

And then our CircleCI config looks like this:

```yaml
  lint--formatting:
    docker:
      - image: clojure:openjdk-16-alpine
    working_directory: /code
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "project.clj" }}
            - v1-dependencies-
      - run:
          name: Zprint
          command: |
            lein zprint ./**/*.clj
```

Thanks for your help and the awesome tools!

## Suggested Musical Pairing

https://soundcloud.com/kingsofleon/golden-restless-age?in=kingsofleon/sets/when-you-see-yourself
